Repository Taskana/taskana, pull requests merged in 2019-12, with the labels that each got.

#763 TSK-963: Add architecture tests to taskana core
  lib/taskana-core/pom.xml
  lib/taskana-core/src/test/java/pro/taskana/ArchitectureTest.java
  pom.xml
Labels: enhancement

#774 TSK-899: now smoke testing documentation
  .travis.yml
  ci/commitPoms.sh
  ci/prepare_db.bat
  ci/verify_docs_alive.sh
  ci/verify_docs_jar.sh
Labels: bug, enhancement

#786 updated some web dependencies
  web/package-lock.json
  web/package.json
Labels: dependencies
