Repository Taskana/taskana, pull requests merged in 2020-01, with the labels that each got.

#793 TSK-1012: Add dynamic list of pojos for pojotesting
  lib/taskana-core/src/main/java/pro/taskana/impl/DaysToWorkingDaysConverter.java
  lib/taskana-core/src/test/java/pro/taskana/PojoTest.java
  lib/taskana-core/src/test/java/pro/taskana/impl/DaysToWorkingDaysConverterTest.java
Labels: enhancement

#802 TSK-889: Replace WorkbasketAccessItemListResource with equivalent Pag…
  history/taskana-simplehistory-spring-test/src/test/java/pro/taskana/doc/api/TaskHistoryEventControllerRestDocumentation.java
  rest/taskana-rest-spring/src/main/java/pro/taskana/rest/WorkbasketAccessItemController.java
  rest/taskana-rest-spring/src/main/java/pro/taskana/rest/WorkbasketController.java
  rest/taskana-rest-spring/src/main/java/pro/taskana/rest/resource/PagedResources.java
  rest/taskana-rest-spring/src/main/java/pro/taskana/rest/resource/WorkbasketAccessItemListResource.java
  rest/taskana-rest-spring/src/main/java/pro/taskana/rest/resource/WorkbasketAccessItemPaginatedListResource.java
  rest/taskana-rest-spring/src/main/java/pro/taskana/rest/resource/WorkbasketAccessItemResourceAssembler.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/ClassificationControllerRestDocumentation.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/TaskControllerRestDocumentation.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/WorkbasketAccessItemControllerRestDocumentation.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/WorkbasketControllerRestDocumentation.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/rest/WorkbasketAccessItemControllerIntTest.java
Labels: enhancement, refactoring

#800 TSK-948: Fix or delete disabled tests
  lib/taskana-core/src/test/java/acceptance/AbstractAccTest.java
  lib/taskana-core/src/test/java/acceptance/classification/QueryClassificationWithPaginationAccTest.java
  lib/taskana-core/src/test/java/acceptance/objectreference/QueryObjectreferencesWithPaginationAccTest.java
  lib/taskana-core/src/test/java/acceptance/task/QueryTasksWithPaginationAccTest.java
  lib/taskana-core/src/test/java/acceptance/workbasket/QueryWorkbasketsWithPaginationAccTest.java
  lib/taskana-core/src/test/java/acceptance/workbasket/WorkbasketQueryWithOrderedPaginationAccTest.java
  lib/taskana-core/src/test/java/pro/taskana/impl/WorkbasketServiceImplTest.java
Labels: enhancement

#846 TSK-948: Delete db2 only irrelevant tests
  lib/taskana-core/src/test/java/acceptance/classification/QueryClassificationWithPaginationAccTest.java
  lib/taskana-core/src/test/java/acceptance/objectreference/QueryObjectreferencesWithPaginationAccTest.java
  lib/taskana-core/src/test/java/acceptance/task/QueryTasksWithPaginationAccTest.java
  lib/taskana-core/src/test/java/acceptance/workbasket/QueryWorkbasketsWithPaginationAccTest.java
Labels: bug

#843 TSK-998: Fix simple linting errors
  web/.eslintrc.js
  web/src/app/administration/access-items-management/access-items-management.component.ts
  web/src/app/administration/administration.module.ts
  web/src/app/administration/classification/details/classification-details.component.spec.ts
  web/src/app/administration/classification/details/classification-details.component.ts
  web/src/app/administration/components/import-export/import-export.component.ts
  web/src/app/administration/components/type-icon/icon-type.component.ts
  web/src/app/administration/services/import-export/import-export.service.ts
  web/src/app/administration/services/saving-workbaskets/saving-workbaskets.service.ts
  web/src/app/administration/workbasket/details/access-items/access-items.component.spec.ts
  web/src/app/administration/workbasket/details/access-items/access-items.component.ts
  web/src/app/administration/workbasket/details/distribution-targets/distribution-targets.component.ts
  web/src/app/administration/workbasket/details/information/workbasket-information.component.ts
  web/src/app/administration/workbasket/master/workbasket-list.component.spec.ts
  web/src/app/app.module.ts
  web/src/app/history/task-query/task-query.component.ts
  web/src/app/models/workbasket-definition.ts
  web/src/app/monitor/report/report.component.ts
  web/src/app/monitor/services/restConnector/rest-connector.service.ts
  web/src/app/monitor/workbasket/monitor-workbasket-query-switcher/monitor-workbasket-query-switcher.component.ts
  web/src/app/monitor/workbasket/monitor-workbaskets.component.ts
  web/src/app/services/alert/alert.service.ts
  web/src/app/services/custom-fields/custom-fields.service.spec.ts
  web/src/app/services/custom-fields/custom-fields.service.ts
  web/src/app/services/domain/domain.service.mock.ts
  web/src/app/services/domain/domain.service.ts
  web/src/app/services/general-modal/general-modal.service.ts
  web/src/app/services/masterAndDetail/master-and-detail.service.ts
  web/src/app/services/orientation/orientation.service.ts
  web/src/app/services/remove-confirmation/remove-confirmation.service.ts
  web/src/app/services/requestInProgress/request-in-progress.service.ts
  web/src/app/services/taskana-engine/taskana-engine.mock.service.ts
  web/src/app/services/taskana-engine/taskana-engine.service.ts
  web/src/app/services/titles/titles.service.ts
  web/src/app/services/tree/tree.service.ts
  web/src/app/shared/classification-types-selector/classification-types-selector.component.ts
  web/src/app/shared/dropdown/dropdown.component.ts
  web/src/app/shared/field-error-display/field-error-display.component.ts
  web/src/app/shared/general-message-modal/general-message-modal.component.ts
  web/src/app/shared/number-picker/number-picker.component.ts
  web/src/app/shared/pagination/pagination.component.ts
  web/src/app/shared/pipes/selectedWorkbasket/seleted-workbasket.pipe.ts
  web/src/app/shared/progress-bar/progress-bar.component.ts
  web/src/app/shared/services/access-ids/access-ids.service.ts
  web/src/app/shared/services/classifications/classification-categories.service.ts
  web/src/app/shared/services/forms/forms-validator.service.ts
  web/src/app/shared/services/upload/upload.service.ts
  web/src/app/shared/sort/sort.component.ts
  web/src/app/shared/tree/tree.component.spec.ts
  web/src/app/shared/type-ahead/type-ahead.component.ts
  web/src/app/workplace/components/code/code.component.ts
  web/src/app/workplace/services/custom-http-interceptor/custom-http-interceptor.service.ts
  web/src/app/workplace/taskdetails/attribute/attribute.component.ts
  web/src/app/workplace/taskdetails/custom/custom-fields.component.ts
  web/src/app/workplace/taskdetails/general-fields-extension/general-fields-extension.component.ts
  web/src/app/workplace/taskmaster/task-list/task-list.component.spec.ts
Labels: refactoring

#860 TSK-987: Fix some problems reported by spotbugs
  history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/configuration/DbSchemaCreator.java
  history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/HistoryQueryImpl.java
  history/taskana-simplehistory-provider/src/test/java/acceptance/AbstractAccTest.java
  history/taskana-simplehistory-provider/src/test/java/acceptance/query/QueryHistoryAccTest.java
  history/taskana-simplehistory-provider/src/test/java/configuration/DbWriter.java
  history/taskana-simplehistory-provider/src/test/java/configuration/TaskanaEngineConfigurationTest.java
  history/taskana-simplehistory-rest-spring/src/main/java/pro/taskana/rest/simplehistory/sampledata/SampleDataGenerator.java
  lib/taskana-cdi/src/test/java/pro/taskana/TaskanaProducersTest.java
  lib/taskana-core/src/main/java/pro/taskana/configuration/DbSchemaCreator.java
  lib/taskana-core/src/main/java/pro/taskana/configuration/TaskanaEngineConfiguration.java
  lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationQueryImpl.java
  lib/taskana-core/src/main/java/pro/taskana/impl/TaskQueryImpl.java
  lib/taskana-core/src/main/java/pro/taskana/impl/TaskanaEngineImpl.java
  lib/taskana-core/src/main/java/pro/taskana/security/CurrentUserContext.java
  lib/taskana-core/src/test/java/acceptance/classification/UpdateClassificationAccTest.java
  lib/taskana-core/src/test/java/pro/taskana/impl/configuration/TaskanaEngineTestConfiguration.java
  lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
  lib/taskana-core/src/test/java/pro/taskana/impl/integration/WorkbasketServiceImplIntAutocommitTest.java
  lib/taskana-spring-example/src/test/java/pro/taskana/TaskanaTransactionIntTest.java
  lib/taskana-spring/src/test/java/pro/taskana/TransactionTest.java
  rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/RestHelper.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/RestHelper.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/rest/TestSchemaNameCustomizable.java
Labels: refactoring

#866 TSK-1024: add LDAP lookup for group by dn
  rest/taskana-rest-spring/src/main/java/pro/taskana/ldap/LdapClient.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/rest/AccessIdControllerIntTest.java
Labels: enhancement

#869 TSK-1025: added assertj dependency to every module
  history/taskana-simplehistory-provider/pom.xml
  history/taskana-simplehistory-spring-test/pom.xml
  lib/taskana-cdi/pom.xml
  lib/taskana-core/pom.xml
  lib/taskana-data/pom.xml
  lib/taskana-spring-example/pom.xml
  lib/taskana-spring/pom.xml
  pom.xml
  rest/taskana-rest-spring-example-common/pom.xml
  rest/taskana-rest-spring-example-wildfly/pom.xml
  rest/taskana-rest-spring/pom.xml
Labels: enhancement

#872 Formatting (automated)
  history/taskana-simplehistory-provider/src/test/java/acceptance/AbstractAccTest.java
  history/taskana-simplehistory-provider/src/test/java/configuration/TaskanaEngineConfigurationTest.java
  history/taskana-simplehistory-spring-test/src/test/java/pro/taskana/doc/api/TaskHistoryEventControllerRestDocumentation.java
  lib/taskana-core/src/main/java/pro/taskana/impl/InternalTaskanaEngine.java
  lib/taskana-core/src/main/java/pro/taskana/impl/TaskanaEngineImpl.java
  lib/taskana-core/src/main/java/pro/taskana/jobs/ScheduledJob.java
  lib/taskana-core/src/main/java/pro/taskana/mappings/JobMapper.java
  lib/taskana-core/src/test/java/pro/taskana/impl/configuration/TaskanaEngineTestConfiguration.java
  rest/taskana-rest-spring/src/main/java/pro/taskana/rest/TaskanaRestExceptionHandler.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/WorkbasketAccessItemControllerRestDocumentation.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/rest/WorkbasketControllerIntTest.java
Labels: refactoring

#881 TSK-1060: Add sort by taskId to TaskQuery
  lib/taskana-core/src/main/java/pro/taskana/TaskQuery.java
  lib/taskana-core/src/main/java/pro/taskana/impl/TaskQueryImpl.java
  lib/taskana-core/src/test/java/acceptance/task/QueryTasksWithSortingAccTest.java
Labels: enhancement

#877 TSK-989 Filter Tasks by planned TimeIntervals (REST)
  rest/taskana-rest-spring/src/main/java/pro/taskana/rest/TaskController.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/rest/TaskControllerIntTest.java
  rest/taskana-rest-spring/src/test/resources/asciidoc/rest-api.adoc
Labels: enhancement

#890 TSK-1024: Make LdapClient more testable
  rest/taskana-rest-spring/src/main/java/pro/taskana/ldap/LdapClient.java
  rest/taskana-rest-spring/src/main/java/pro/taskana/ldap/LdapConfiguration.java
  rest/taskana-rest-spring/src/main/java/pro/taskana/ldap/LdapSettings.java
  rest/taskana-rest-spring/src/test/java/pro/taskana/ldap/LdapClientTest.java
Labels: refactoring

#887 TSK-1062: removed rawtype from MapTypeHandler
  lib/taskana-core/src/main/java/pro/taskana/impl/persistence/MapTypeHandler.java
Labels: enhancement
